server:
  port: 9090

spring:
  redis:
    host: redis
    port: 6379
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      default-filters:
        - name: SpringCloudGatewayGlobalFilter
      routes:
        - id: ms1
          uri: http://localhost:8080/
          predicates:
            - Path=/ms1/**
        - id: ms2
          uri: http://localhost:8081/
          predicates:
            - Path=/ms2/**
#          filters:
#            - name: RequestRateLimiter
#              args:
##                key-resolver: "#{@userKeyResolver}"
#                redis-rate-limiter:
#                  replenishRate: 2
#                  burstCapacity: 2
#                  requestedTokens: 1
#            - name: RateLimitingForAdminUserFilter
#            - name: SpringCloudGatewayPreFilter
#            - name: SpringCloudGatewayPostFilter